craco.config.js
package-lock.json
package.json
src/index.css
src/index.js
tailwind.config.js

Created a few files associated with installing Tailwind. All tests pass.

Add tailwind

---

src/components/cocktail.js
src/components/logged_in_app.js
src/components/show_page.js
src/test/cocktail.test.js
src/test/show_page.test.js

- user can see cocktail details on recommendation page
- user can see cocktail details on details page after search
- Tagline can be changed depending on which page the user is on

Cocktail show page

---

src/actions/auth_actions/confirm_login_action.js
src/components/sign_in_button.js
src/constants.js
src/core/app_actions.js

authentication is not connected to backend
- authentication connects to backend
This code works, but I don't know if it is 'good' frontend code. I would love to work with @redferret to refactor for better FE best practices.

Twf.landing page authentication

---

src/components/landing.js
src/components/white_logo.js

There are scroll bars on the landing page. I changed the styles to have them removed. I also added margin to the white logo to give it space from the edges

Style changes to landing page

---

src/actions/action_repo.js
src/actions/auth_actions/logout_action.js
src/components/app.js
src/components/authenticated_route.js
src/components/header.js
src/components/sign_out_button.js
src/constants.js
src/stores/auth_store.js

Issue Number: 
closes #
- Adds a sign out button to log the user out, redirects user back to the landing page.
-

Add sign out button

---

src/components/sign_out_button.js

styled logout button

---

src/__mocks__/cocktails.js
src/components/cocktail.js
src/components/search.js
src/components/search_results.js
src/components/show_page.js
src/components/yelp_search.js
src/service/cocktail.js
src/test/search_results.test.js
src/test/yelp_search.test.js
tailwind.config.js

Issue Number: 
closes #34
can search with yelp

Yelp search

---

src/components/cocktail.js

Just commented out the social component

take out social buttons

---

src/components/cocktail.js
src/components/onboard.js
src/components/recommendation_button.js
src/components/search_results.js
src/components/show_page.js
src/components/stars.js
src/components/starter_cocktails.js
src/test/onboard.test.js

Issue Number: 
closes #17 
- Updates onboard page to pull from BE data
- Makes recommendation button grey if user has not yet rated enough cocktails, black if they have done so

Update onboard page for live data (and button alternation)

---

public/index.html
src/components/app.js
src/components/dashboard.js
src/components/show_page.js
src/test/yelp_search.test.js

Issue Number: 
closes #35 
Button for dashboard page

Dashboard page

---

src/components/app.js

Issue Number: 
closes #50 
auth user is redirected to dashboard if no route is matched

auth user is redirected to dashboard page if no routes are matched

---

src/components/search_results.js
src/service/cocktail.js

Issue Number: 
closes #51
now shows if there are no results

shows no results on show page if there are none

---

src/components/authenticated_route.js

after fixing an issue with redirects a bug cropped up where the landing page component was not being rendered. bux fixed

bug with redirect and routing

---

src/components/recommendation_button.js
src/components/show_page.js
src/components/stars.js
src/components/starter_cocktails.js

Made recommendation button disabled and gray until user has rated 5 cocktails
Issue Number: 
closes #
- 
- 
-

Make recommendation button enabled once 5 are rated

---

src/components/cocktail.js
src/components/starter_cocktails.js

- cursor does not indicate that you can interact with stars
- cursor is a pointer when hovering over stars

make cursor point when hovering on stars

---

src/components/yelp_search.js

Issue Number: 
closes #
- 
- 
-

Fix address spacing in Yelp search

---

README.md

Issue Number: 
closes #
- 
- 
-

Spell our names correctly

---

src/components/age_verification_modal.js
src/components/landing.js

Age verification on landing page.
Issue Number: 
closes #
No new behavior, just refactored modal to make the code clean. **Richard worked on refactoring.**
- 
- 
-

Refactor modal

---

src/components/cocktail.js
src/components/dashboard.js
src/components/show_page.js
src/components/stars.js

'fix' bug where cocktail component would not update/rerender 

fix bug with components not rerendering

---

src/components/dashboard.js

Literally just removed the one word since it doesn't make sense here. 
Issue Number: 
closes #
- Removes unnecessary word
-

Remove the word 'glass'

---

src/components/landing.js
src/components/show_page.js
src/stores/auth_mall.js

This PR fixes the blank page after login bug. The lifecycle of logging in wasn't updating the mall correctly and during this lifecycle the landing page doesn't need to mall but just the auth context to determine if the user is authed.
Second bug fix I found was users were able to navigate to the `/onboard` where in the past it would not let users that were already onboarded access this route.
- When a user logs in they are presented a black page.
- There is a bug where user can still navigate to `/onboard` even if they aren't new
- When user logs in they no longer see the blank page
- Users that are not new won't see the onboard anymore

Hotfix authentication
